spring:
  output:
    ansi:
      enabled: DETECT 
  config:
    activate:
      on-profile:
      - local

logging:
  # file: /logs/application-debug.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info
