spring:
  config:
    activate:
      on-profile:
      - local
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=1
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org:
      springframework: DEBUG
