spring:
  output:
    ansi:
      enabled: DETECT 
  config:
    activate:
      on-profile:
      - local
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=1
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  # file: /logs/application-debug.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info
